MAKAR-iOS/MAKAR-iOS

MAKAR.xcodeproj/project.pbxproj, MAKAR/App/AppDependency.swift, MAKAR/App/SceneDelegate.swift, MAKAR/Extension/MakarColor.xcassets/point colors/kakao_yellow.colorset/Contents.json, MAKAR/Extension/UIColor+Extension.swift, MAKAR/Presentation/Base/BaseRouter.swift, MAKAR/Presentation/Home/HomeView.swift, MAKAR/Presentation/Home/HomeViewController.swift, MAKAR/Presentation/Login/LoginView.swift, MAKAR/Presentation/Login/LoginViewController.swift, MAKAR/Presentation/Splash/SplashView.swift, MAKAR/Presentation/Splash/SplashViewController.swift, MAKAR/Support/Info.plist
#5 
- SplashView, SplashViewController 구현
- LoginView, LoginViewController 구현
- Localization 설정
- splash 후 rootView, login 후 rootView 변경
- BaseRouter 연결
https://github.com/MAKAR-iOS/MAKAR-iOS/assets/84546438/565e03e5-63ee-404b-80f0-ff9db7a6e454
=> [Feat] SplashViewController, LoginViewController구현

MAKAR/Extension/MakarColor.xcassets/text colors/lightgray4.colorset/Contents.json, MAKAR/Extension/MakarColor.xcassets/text colors/lightgray6.colorset/Contents.json, MAKAR/Extension/SignUpTextField.swift, MAKAR/Extension/UIButton+Extension.swift, MAKAR/Extension/UIColor+Extension.swift, MAKAR/Extension/UITextField+Extension.swift, MAKAR/Presentation/Home/Cell/FavoriteRouteCollectionViewCell.swift, MAKAR/Presentation/Home/Cell/RecentRouteCollectionViewCell.swift, MAKAR/Presentation/Notification/MakarNotiView.swift, MAKAR/Presentation/Notification/NotificationViewController.swift, MAKAR/Presentation/TabBar/TabBarViewController.swift
=> [Feat] 탭바 구조 리팩토링

MAKAR/Extension/SignUpTextField.swift, MAKAR/Presentation/Auth/SignUp/SignUpView.swift, MAKAR/Presentation/Auth/SignUp/SignUpViewController.swift
=> [Feat] SignUp EmailTextField 추가

MAKAR/Extension/SignUpTextField.swift, MAKAR/Networking/Auth/AuthAPI.swift, MAKAR/Networking/Auth/AuthResponse.swift, MAKAR/Networking/Auth/AuthService.swift, MAKAR/Networking/Network/NetworkService.swift, MAKAR/Networking/Network/URLConst.swift, MAKAR/Presentation/Auth/SignIn/SignInView.swift, MAKAR/Presentation/Auth/SignIn/SignInViewController.swift, MAKAR/Presentation/Auth/SignUp/SignUpView.swift, MAKAR/Presentation/Auth/SignUp/SignUpViewController.swift, MAKAR/Support/Info.plist
=> [Feat] Auth API 연결

MAKAR.xcodeproj/project.pbxproj, MAKAR/Networking/Auth/AuthResponse.swift, MAKAR/Networking/Noti/NotiAPI.swift, MAKAR/Networking/Noti/NotiService.swift, MAKAR/Networking/Route/RouteAPI.swift, MAKAR/Networking/Route/RouteService.swift, MAKAR/Networking/Station/StationAPI.swift, MAKAR/Networking/Station/StationService.swift, MAKAR/Presentation/Home/HomeView.swift, MAKAR/Presentation/MyPage/FavoriteRoute/FavoriteRouteTableViewCell.swift
closed #54 
- 즐겨찾는 경로 리스트 tableview cell 환승 정보 제거
=> [Chore] 즐겨찾는 경로 리스트 tableview cell 수정

MAKAR/Presentation/Home/Cell/FavoriteRouteCollectionViewCell.swift, MAKAR/Presentation/Home/Cell/RecentRouteCollectionViewCell.swift, MAKAR/Presentation/Home/HomeView.swift, MAKAR/Presentation/Home/HomeViewController.swift, MAKAR/Presentation/MyPage/FavoriteStation/SearchStation/HomeSearchStationViewController.swift, MAKAR/Presentation/MyPage/FavoriteStation/SearchStation/SchoolSearchStationViewController.swift, MAKAR/Presentation/Search/SearchStation/DestinationSearchStationViewController.swift, MAKAR/Presentation/Search/SearchStation/SourceSearchStationViewController.swift
closed #56 
- 경로 설정 시에도 즐겨찾는 경로, 최근 경로 UI 유지
=> [Chore] 경로 설정 시 즐겨찾는 경로, 최근 경로 리스트 유지

MAKAR/Extension/Route/RouteData.swift, MAKAR/Presentation/Home/Cell/RecentRouteCollectionViewCell.swift, MAKAR/Presentation/Home/HomeViewController.swift, MAKAR/Presentation/MyRoute/MyRouteView.swift, MAKAR/Presentation/Search/SearchRoute/Cell/SearchRouteTableViewCell.swift
closed #62 
- MyRouteView, SearchRouteTableViewCell Date format 변경
- RouteData 경로 설정 날짜 필드 제거
=> [Chore] 경로 검색 리스트 TableViewCell Date Format 변경

MAKAR.xcodeproj/project.pbxproj, MAKAR/App/AppDelegate.swift, MAKAR/Extension/UIKit+Extension/UNUserNotificationCenter+Extension.swift, MAKAR/Presentation/Home/HomeViewController.swift
closed #64 
- UNUserNotificationCenter extension 설정
- 막차 Notification 구현
- 하차 Notification 구현
=> [Feat] Notification 구현

MAKAR.xcodeproj/project.pbxproj, MAKAR/Extension/Base/BaseRouter.swift, MAKAR/Extension/Base/SearchStation/BaseSearchStationViewController.swift, MAKAR/Extension/Route/LineNumMap.swift, MAKAR/Networking/Network/NetworkService.swift, MAKAR/Networking/Route/RouteAPI.swift, MAKAR/Networking/Route/RouteListResponse.swift, MAKAR/Networking/Route/RouteResponse.swift, MAKAR/Networking/Route/RouteService.swift, MAKAR/Presentation/Search/SearchRoute/SearchRouteViewController.swift, MAKAR/Presentation/Search/SearchStation/Cell/SearchStationTableViewCell.swift, MAKAR/Presentation/Search/SearchStation/DestinationSearchStationViewController.swift, MAKAR/Presentation/Search/SearchStation/SourceSearchStationViewController.swift
=> [Feat] 경로 리스트 검색 API 연결

MAKAR/Networking/Network/NetworkService.swift, MAKAR/Networking/Noti/NotiAPI.swift, MAKAR/Networking/Noti/NotiResponse.swift, MAKAR/Networking/Noti/NotiService.swift, MAKAR/Presentation/Home/HomeViewController.swift, MAKAR/Presentation/Notification/NotificationViewController.swift
closed #72 
- 알림 리스트 조회 API 연결
- 막차 알림 추가 API 연결
- 막차 알림 삭제 API 연결
- 하차 알림 삭제 API 연결
- del URI : {notiId} pathvariable 추가하기
- notiVC : 알림 리스트 조회 후 makarTableView.reloadData()
=> [Feat] 막차, 하차 알림 추가, 조회, 삭제 API 연결

MAKAR.xcodeproj/project.pbxproj, MAKAR/Networking/Route/RouteListResponse.swift, MAKAR/Networking/Route/RouteService.swift, MAKAR/Presentation/MyRoute/MyRouteView.swift, MAKAR/Presentation/Search/SearchRoute/Cell/SearchRouteProgressView.swift, MAKAR/Presentation/Search/SearchRoute/Cell/SearchRouteTableViewCell.swift, MAKAR/Presentation/Search/SearchRoute/Cell/SubRouteTextView.swift, MAKAR/Presentation/Search/SearchRoute/EmptyResultView.swift, MAKAR/Presentation/Search/SearchRoute/SearchRouteViewController.swift
#71 
경로 리스트 검색 및 설정 API를 연결합니다.
=> [Feat] 경로 리스트 검색 및 설정 API 연결

MAKAR.xcodeproj/project.pbxproj, MAKAR/Networking/Home/HomeAPI.swift, MAKAR/Networking/Home/HomeResponse.swift, MAKAR/Networking/Home/HomeService.swift, MAKAR/Networking/Network/NetworkService.swift, MAKAR/Networking/Network/URLConst.swift, MAKAR/Networking/Route/RouteResponse.swift, MAKAR/Networking/Route/RouteService.swift, MAKAR/Presentation/Home/HomeViewController.swift
closed #74 
- 홈 화면 조회 API 연결
- 경로 삭제 API 연결
- 경로 미지정 시 홈 화면 조회 pathError 버그
- 홈 화면 조회 API 사용 후 component change 시간 감소 필요
=> [Feat] 홈 화면 조회, 경로 삭제 API 연결

MAKAR.xcodeproj/project.pbxproj, MAKAR/Networking/Station/FavoriteStationResponse.swift, MAKAR/Networking/Station/StationAPI.swift, MAKAR/Networking/Station/StationResponse.swift, MAKAR/Networking/Station/StationService.swift, MAKAR/Presentation/MyPage/FavoriteStation/FavoriteStationView.swift, MAKAR/Presentation/MyPage/FavoriteStation/FavoriteStationViewController.swift, MAKAR/Presentation/MyPage/FavoriteStation/SearchStation/HomeSearchStationViewController.swift, MAKAR/Presentation/MyPage/FavoriteStation/SearchStation/SchoolSearchStationViewController.swift, MAKAR/Presentation/Search/SearchRoute/SearchRouteViewController.swift, MAKAR/Presentation/Search/SearchStation/SourceSearchStationViewController.swift
=> [Feat] 즐겨찾는 역 API 연결

MAKAR/Networking/Auth/AuthAPI.swift, MAKAR/Networking/Auth/AuthResponse.swift, MAKAR/Networking/Auth/AuthService.swift, MAKAR/Networking/Network/URLConst.swift, MAKAR/Presentation/MyPage/MyPageViewController.swift
=> [Feat] 로그아웃 API 연결

MAKAR/Networking/Station/StationResponse.swift, MAKAR/Presentation/Home/HomeViewController.swift, MAKAR/Presentation/MyPage/FavoriteStation/FavoriteStationViewController.swift, MAKAR/Presentation/Search/SearchRoute/SearchRouteViewController.swift, MAKAR/Presentation/Search/SearchStation/DestinationSearchStationViewController.swift
=> [Fix] 역 검색 텍스트 전달 오류 수정

MAKAR/App/UserDefault/UserDefaultHandler.swift, MAKAR/Networking/Route/RouteListResponse.swift, MAKAR/Networking/Route/RouteService.swift, MAKAR/Presentation/Home/HomeViewController.swift, MAKAR/Presentation/Search/SearchRoute/SearchRouteViewController.swift
=> [Feat] UserDefault RouteId 추가

MAKAR/Networking/Route/DeleteRouteListResponse.swift, MAKAR/Networking/Route/RouteListResponse.swift, MAKAR/Networking/Route/RouteService.swift, MAKAR/Presentation/Home/HomeView.swift, MAKAR/Presentation/Home/HomeViewController.swift, MAKAR/Presentation/MyRoute/MyRouteViewController.swift
=> [Feat] EmptyView 구현

MAKAR/Extension/ImageLiteral.swift, MAKAR/Presentation/Home/Cell/FavoriteRouteCollectionViewCell.swift, MAKAR/Presentation/Home/Cell/RecentRouteCollectionViewCell.swift, MAKAR/Presentation/Home/HomeViewController.swift, MAKAR/Presentation/MyPage/FavoriteStation/FavoriteStationViewController.swift, MAKAR/Presentation/Search/SearchRoute/SearchRouteView.swift, MAKAR/Presentation/Search/SearchRoute/SearchRouteViewController.swift, MAKAR/Presentation/Search/SearchStation/DestinationSearchStationViewController.swift, MAKAR/Presentation/Search/SearchStation/SourceSearchStationViewController.swift
=> [Fix] 기타 오류 해결

MAKAR.xcodeproj/project.pbxproj, MAKAR/Networking/Noti/NotiAPI.swift, MAKAR/Presentation/Notification/NotificationViewController.swift
=> [Fix] 알림 API 연결 수정

MAKAR/Presentation/MyPage/MyPageViewController.swift
=> fix: cell 클릭시 색상 변경 막기
